# DockerFile for an environment into which firedrake can be installed.
# Based on https://github.com/firedrakeproject/firedrake/blob/master/docker/Dockerfile.env
# build cmd:
#
# $ docker build -f Dockerfile.env --tag lrtfm/firedrake-env:latest .
#

FROM ubuntu:20.04

# This DockerFile is looked after by
MAINTAINER Zongze Yang <yangzongze@gmail.com>

# Update and install required packages for Firedrake
USER root
RUN apt-get update \
    && apt-get -y dist-upgrade \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata \
    && apt-get -y install curl vim docker.io \
                 openssh-client build-essential autoconf automake pkg-config \
                 cmake gfortran git libopenblas-serial-dev \
                 libtool python3-dev python3-pip python3-tk python3-venv \
                 python3-requests zlib1g-dev libboost-dev sudo \
                 bison flex \
                 liboce-ocaf-dev \
                 swig graphviz \
                 libgmsh4 \
                 bear clangd \
    && rm -rf /var/lib/apt/lists/*

# Use a more sane locale
ENV LC_ALL C.UTF-8

# Set up user so that we do not run as root
RUN useradd -m -s /bin/bash -G sudo firedrake && \
    echo "firedrake:docker" | chpasswd && \
    echo "firedrake ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    ldconfig

USER firedrake
WORKDIR /home/firedrake

